#! /bin/bash
CARTO_DIRECTORY=$CARTO_DIRECTORY
SHARED_DIRECTORY=$SHARED_DIRECTORY
MAPNIK_DEST="$SHARED_DIRECTORY"/"$MAPNIK_DEST_FILE"
CARTO_PROJECT_FILE_PATH="$CARTO_DIRECTORY"/"$CARTO_PROJECT_FILE"
BASE_DATA_DIR=$BASE_DATA_DIR
BASE_DATA_DIR_PATH="$SHARED_DIRECTORY"/"$BASE_DATA_DIR"
POSTGRES_RENDER_DATABASE=$POSTGRES_RENDER_DATABASE
POSTGRES_RENDER_USER=$POSTGRES_RENDER_USER
POSTGRES_RENDER_PASSWORD=$POSTGRES_RENDER_PASSWORD
POSTGRES_SERVER=$POSTGRES_SERVER

# Clean up the project file to use our base directory
cd /src/openstreetmap-carto/ && git checkout project.mml && cd /
perl -pi -e "s|^([\s]{1,})file: data/|\1file: $BASE_DATA_DIR_PATH/|g" $CARTO_PROJECT_FILE_PATH
perl -pi -e "s|^([\s]{1,})dbname: \"(.+)\"|\1dbname: \"$POSTGRES_RENDER_DATABASE\"\n\1host: \"$POSTGRES_SERVER\"\n\1user: \"$POSTGRES_RENDER_USER\"\n\1password: \"$POSTGRES_RENDER_PASSWORD\"|g" $CARTO_PROJECT_FILE_PATH

cp -r "$CARTO_DIRECTORY"/symbols/ /mnt
echo "Creating Mapnik XML file" && \
  carto $CARTO_PROJECT_FILE_PATH > $MAPNIK_DEST && \
  echo "Mapnik File Created ("`du -k "$MAPNIK_DEST" | cut -f1`"k)"
