#!/bin/bash

# These all come from tbe environment file
CARTO_DIRECTORY=$CARTO_DIRECTORY
CARTO_STYLE_SCRIPT=$CARTO_STYLE_SCRIPT
CARTO_TRANSFORM_SCRIPT=$CARTO_TRANSFORM_SCRIPT
OSM2PGSQL_IMPORT_MEMORY=$OSM2PGSQL_IMPORT_MEMORY
OSM2PGSQL_IMPORT_PROCESSES=$OSM2PGSQL_IMPORT_PROCESSES
POSTGRES_RENDER_DATABASE=$POSTGRES_RENDER_DATABASE
POSTGRES_RENDER_PASSWORD=$POSTGRES_RENDER_PASSWORD
POSTGRES_RENDER_USER=$POSTGRES_RENDER_USER
POSTGRES_SERVER=$POSTGRES_SERVER
SAMPLE_DATASET_URL=$SAMPLE_DATASET_URL
SHARED_DIRECTORY=$SHARED_DIRECTORY
BASE_DATA_DIR=$BASE_DATA_DIR
BASE_DATA_DIR_PATH="$SHARED_DIRECTORY"/"$BASE_DATA_DIR"
SAMPLE_DATASET_FILE=sample_dataset.pbf

# Download the sample dataset
mkdir -p $BASE_DATA_DIR_PATH
wget -O "$BASE_DATA_DIR_PATH"/"$SAMPLE_DATASET_FILE" "$SAMPLE_DATASET_URL"

# Load the sample data into the database
export PGUSER=$POSTGRES_USER
export PGPASSWORD=$POSTGRES_PASSWORD

# Load data into postgres
osm2pgsql \
  -H $POSTGRES_SERVER \
  -d $POSTGRES_RENDER_DATABASE \
  --create \
  --slim \
  -G \
  --hstore \
  --tag-transform-script "$CARTO_DIRECTORY"/"$CARTO_TRANSFORM_SCRIPT" \
  -C $OSM2PGSQL_IMPORT_MEMORY \
  --number-processes $OSM2PGSQL_IMPORT_PROCESSES \
  -S "$CARTO_DIRECTORY"/"$CARTO_STYLE_SCRIPT" \
  "$BASE_DATA_DIR_PATH"/"$SAMPLE_DATASET_FILE"
