#!/bin/bash

# These all come from the environment file
POSTGRES_USER=$POSTGRES_USER
POSTGRES_PASSWORD=$POSTGRES_PASSWORD

POSTGRES_RENDER_USER=$POSTGRES_RENDER_USER
POSTGRES_RENDER_PASSWORD=$POSTGRES_RENDER_PASSWORD
POSTGRES_RENDER_DATABASE=$POSTGRES_RENDER_DATABASE
POSTGIS_SERVER=$POSTGRES_SERVER

export PGPASSWORD=$POSTGRES_PASSWORD

# Create the Render User
psql -U $POSTGRES_USER -h $POSTGIS_SERVER -c "CREATE USER $POSTGRES_RENDER_USER WITH PASSWORD '$POSTGRES_RENDER_PASSWORD'"
psql -U $POSTGRES_USER -h $POSTGIS_SERVER -c "ALTER USER $POSTGRES_RENDER_USER WITH SUPERUSER;"

# Create the render database
psql -U $POSTGRES_USER -h $POSTGIS_SERVER -c "CREATE DATABASE \"$POSTGRES_RENDER_DATABASE\" OWNER \"$POSTGRES_RENDER_USER\" ENCODING 'UTF8';"

# Geospatially enable the new database
psql -U $POSTGRES_USER -d $POSTGRES_RENDER_DATABASE -h $POSTGIS_SERVER -c "CREATE EXTENSION postgis;";
psql -U $POSTGRES_USER -d $POSTGRES_RENDER_DATABASE -h $POSTGIS_SERVER -c "CREATE EXTENSION hstore;";
psql -U $POSTGRES_USER -d $POSTGRES_RENDER_DATABASE -h $POSTGIS_SERVER -c "ALTER TABLE geometry_columns OWNER TO $POSTGRES_RENDER_USER;";
psql -U $POSTGRES_USER -d $POSTGRES_RENDER_DATABASE -h $POSTGIS_SERVER -c "ALTER TABLE spatial_ref_sys OWNER TO $POSTGRES_RENDER_USER;";
